### ISSUE TITLE
Dockerfile: Upgrade to max-base v1.1.3

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Toxic-Comment-Classifier#4]
https://github.com/IBM/MAX-Toxic-Comment-Classifier/blob/master/Dockerfile#L1 to take advantage of the CORS bug fix.

**Comment by splovyt** [comment]
Fixed in https://github.com/IBM/MAX-Toxic-Comment-Classifier/commit/25c7aea4aa4bfa9dbc3ea6800e3d4c516bc8312d. Thanks for the patch Patrick.

Also, cut a new `v1.0.1` release for this patch.
